import type { SettingCategory } from "@/types/settings-schema";
import { useSettingsStore } from "@/stores/settings";
import IconLucideType from "~icons/lucide/type";

const lyricStyleCategory: SettingCategory = {
  id: "lyricStyle",
  icon: IconLucideType,
  sections: [
    {
      id: "lyricGeneral",
      items: [
        {
          key: "adaptiveFontSize",
          type: "switch",
          binding: { store: "settings", path: "lyric.adaptiveFontSize" },
          defaultValue: true,
        },
        {
          key: "fontSize",
          type: "slider",
          binding: { store: "settings", path: "lyric.fontSize" },
          min: 30,
          max: 64,
          step: 1,
          defaultValue: 48,
          marks: { 30: "30", 48: "48", 64: "64" },
        },
        {
          key: "fontWeight",
          type: "slider",
          binding: { store: "settings", path: "lyric.fontWeight" },
          min: 100,
          max: 900,
          step: 100,
          defaultValue: 700,
          marks: { 100: "100", 400: "400", 700: "700", 900: "900" },
        },
        {
          key: "fontFamily",
          type: "select",
          binding: { store: "settings", path: "lyric.fontFamily" },
          options: [
            { value: "Arial", labelKey: "settings.fontFamily.Arial" },
            { value: "Helvetica", labelKey: "settings.fontFamily.Helvetica" },
            { value: "system-ui", labelKey: "settings.fontFamily.system-ui" },
            { value: "Microsoft YaHei", labelKey: "settings.fontFamily.Microsoft YaHei" },
            { value: "PingFang SC", labelKey: "settings.fontFamily.PingFang SC" },
            { value: "Source Han Sans SC", labelKey: "settings.fontFamily.Source Han Sans SC" },
            { value: "Noto Sans SC", labelKey: "settings.fontFamily.Noto Sans SC" },
            { value: "Segoe UI", labelKey: "settings.fontFamily.Segoe UI" },
            { value: "Roboto", labelKey: "settings.fontFamily.Roboto" },
            { value: "SF Pro Display", labelKey: "settings.fontFamily.SF Pro Display" },
          ],
          defaultValue: "Arial",
        },
        {
          key: "showTranslation",
          type: "switch",
          binding: { store: "settings", path: "lyric.showTranslation" },
          defaultValue: true,
        },
        {
          key: "showRomanization",
          type: "switch",
          binding: { store: "settings", path: "lyric.showRomanization" },
          defaultValue: true,
        },
      ],
    },
    {
      id: "lyricDisplay",
      items: [
        {
          key: "enableWordHighlight",
          type: "switch",
          binding: { store: "settings", path: "lyric.enableWordHighlight" },
          defaultValue: true,
        },
        {
          key: "enableFloatAnimation",
          type: "switch",
          binding: { store: "settings", path: "lyric.enableFloatAnimation" },
          defaultValue: false,
        },
        {
          key: "enableEmphasizeEffect",
          type: "switch",
          binding: { store: "settings", path: "lyric.enableEmphasizeEffect" },
          defaultValue: false,
        },
        {
          key: "enableBlur",
          type: "switch",
          binding: { store: "settings", path: "lyric.enableBlur" },
          defaultValue: false,
        },
        {
          key: "hidePassedLines",
          type: "switch",
          binding: { store: "settings", path: "lyric.hidePassedLines" },
          defaultValue: false,
        },
      ],
    },
    {
      id: "lyricSpring",
      items: [
        {
          key: "springPreset",
          type: "select",
          binding: { store: "settings", path: "lyric.springPreset" },
          options: [
            { value: "default", labelKey: "settings.springPreset.default" },
            { value: "smooth", labelKey: "settings.springPreset.smooth" },
            { value: "responsive", labelKey: "settings.springPreset.responsive" },
            { value: "jello", labelKey: "settings.springPreset.jello" },
            { value: "heavy", labelKey: "settings.springPreset.heavy" },
            { value: "noBounce", labelKey: "settings.springPreset.noBounce" },
            { value: "custom", labelKey: "settings.springPreset.custom" },
          ],
          defaultValue: "default",
          childrenCondition: () => useSettingsStore().lyric.springPreset === "custom",
          children: [
            {
              key: "springMass",
              type: "slider",
              binding: { store: "settings", path: "lyric.springMass" },
              min: 0.1,
              max: 5,
              step: 0.1,
              defaultValue: 0.9,
              marks: { 0.1: "0.1", 0.9: "0.9", 5: "5" },
            },
            {
              key: "springDamping",
              type: "slider",
              binding: { store: "settings", path: "lyric.springDamping" },
              min: 1,
              max: 50,
              step: 0.5,
              defaultValue: 15,
              marks: { 1: "1", 15: "15", 50: "50" },
            },
            {
              key: "springStiffness",
              type: "slider",
              binding: { store: "settings", path: "lyric.springStiffness" },
              min: 10,
              max: 300,
              step: 5,
              defaultValue: 90,
              marks: { 10: "10", 90: "90", 300: "300" },
            },
          ],
        },
      ],
    },
    {
      id: "lyricLayout",
      items: [
        {
          key: "alignPosition",
          type: "slider",
          binding: { store: "settings", path: "lyric.alignPosition" },
          min: 0.1,
          max: 0.9,
          step: 0.05,
          defaultValue: 0.35,
          marks: { 0.1: "0.1", 0.35: "0.35", 0.9: "0.9" },
        },
        {
          key: "wordFadeWidth",
          type: "slider",
          binding: { store: "settings", path: "lyric.wordFadeWidth" },
          min: 0.1,
          max: 1,
          step: 0.1,
          defaultValue: 0.5,
          marks: { 0.1: "0.1", 0.5: "0.5", 1: "1" },
        },
        {
          key: "inactiveAlpha",
          type: "slider",
          binding: { store: "settings", path: "lyric.inactiveAlpha" },
          min: 0,
          max: 1,
          step: 0.05,
          defaultValue: 0.3,
          marks: { 0: "0", 0.3: "0.3", 1: "1" },
        },
        {
          key: "lyricScrollDirection",
          type: "select",
          binding: { store: "settings", path: "lyric.lyricScrollDirection" },
          options: [
            { value: "natural", labelKey: "settings.lyricScrollDirection.natural" },
            { value: "reverse", labelKey: "settings.lyricScrollDirection.reverse" },
          ],
          defaultValue: "reverse",
        },
      ],
    },
    {
      id: "fanLyrics",
      tag: { text: "Beta" },
      items: [
        {
          key: "enableFanLyrics",
          type: "switch",
          binding: { store: "settings", path: "player.enableFanLyrics" },
          defaultValue: false,
          children: [
            {
              key: "fanLyricsAngle",
              type: "slider",
              binding: { store: "settings", path: "player.fanLyricsAngle" },
              defaultValue: 60,
              min: -90,
              max: 90,
              step: 1,
              marks: { "-90": "-90", "-30": "-30", 0: "0", 30: "30", 60: "60", 90: "90" },
            },
            {
              key: "fanLyricsMaxLines",
              type: "slider",
              binding: { store: "settings", path: "player.fanLyricsMaxLines" },
              defaultValue: 7,
              min: 3,
              max: 12,
              step: 1,
              marks: { 3: "3", 7: "7", 12: "12" },
            },
            {
              key: "fanLyricsLineHeight",
              type: "slider",
              binding: { store: "settings", path: "player.fanLyricsLineHeight" },
              defaultValue: 96,
              min: 32,
              max: 140,
              step: 2,
              marks: { 32: "32", 96: "96", 140: "140" },
            },
            {
              key: "fanLyricsMinScale",
              type: "slider",
              binding: { store: "settings", path: "player.fanLyricsMinScale" },
              defaultValue: 0.78,
              min: 0.3,
              max: 1,
              step: 0.02,
              marks: { 0.3: "0.3", 0.78: "0.78", 1: "1" },
            },
            {
              key: "fanLyricsMinOpacity",
              type: "slider",
              binding: { store: "settings", path: "player.fanLyricsMinOpacity" },
              defaultValue: 0,
              min: 0,
              max: 1,
              step: 0.05,
              marks: { 0: "0", 0.3: "0.3", 1: "1" },
            },
            {
              key: "fanLyricsMaxBlur",
              type: "slider",
              binding: { store: "settings", path: "player.fanLyricsMaxBlur" },
              defaultValue: 7,
              min: 0,
              max: 8,
              step: 0.5,
              marks: { 0: "0", 4: "4", 8: "8" },
            },
            {
              key: "fanLyricsEnableBackground",
              type: "switch",
              binding: { store: "settings", path: "player.fanLyricsEnableBackground" },
              defaultValue: true,
            },
            {
              key: "fanLyricsEnableGlow",
              type: "switch",
              binding: { store: "settings", path: "player.fanLyricsEnableGlow" },
              defaultValue: true,
            },
          ],
        },
      ],
    },
  ],
};

export default lyricStyleCategory;
